In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Bengaluru_House_Data.csv')

In [3]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [4]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [5]:
df.drop("society",axis = 1, inplace= True)

In [6]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.0,17.00

In [7]:
df.isnull().sum()

area_type         0
availability      0
location          1
size             16
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum()

area_type       0
availability    0
location        0
size            0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [11]:
df.shape

(12710, 8)

In [12]:
df.head(1)

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07

In [18]:
def query_houses(dataframe, location = None, max_price = None, min_sqft = None):
    filtered_df = dataframe.copy()
    
    if location:
        filtered_df = filtered_df[filtered_df['location'].str.contains(location, case = False)]
        
        if max_price is not None:
            filtered_df = filtered_df[filtered_df['price'] <= max_price]
            
        if min_sqft is not None:
            filtered_df = filtered_df[filtered_df['total_sqft'] >= min_sqft]
            
        return filtered_df
    
results = query_houses(df, location="Whitefield",max_price=231.00, min_sqft=1521)
print(results.head())

                area_type   availability    location   size  total_sqft  bath  \
10   Super built-up  Area         18-Feb  Whitefield  3 BHK      1800.0   2.0
27         Built-up  Area         20-Dec  Whitefield  3 BHK      1610.0   3.0
52         Built-up  Area  Ready To Move  Whitefield  3 BHK      2010.0   3.0
400  Super built-up  Area  Ready To Move  Whitefield  3 BHK      1910.0   3.0
401  Super built-up  Area  Ready To Move  Whitefield  4 BHK      3252.0   4.0

     balcony  price
10       2.0   70.0
27       2.0   81.0
52       2.0   91.0
400      2.0  161.0
401      1.0  230.0

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12710 entries, 0 to 13319
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     12710 non-null  object
 1   availability  12710 non-null  object
 2   location      12710 non-null  object
 3   size          12710 non-null  object
 4   total_sqft    12710 non-null  object
 5   bath          12710 non-null  float64
 6   balcony       12710 non-null  float64
 7   price         12710 non-null  float64
dtypes: float64(3), object(5)
memory usage: 893.7+ KB

In [16]:
df['total_sqft'] = pd.to_numeric(df['total_sqft'], errors='coerce')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12710 entries, 0 to 13319
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     12710 non-null  object
 1   availability  12710 non-null  object
 2   location      12710 non-null  object
 3   size          12710 non-null  object
 4   total_sqft    12524 non-null  float64
 5   bath          12710 non-null  float64
 6   balcony       12710 non-null  float64
 7   price         12710 non-null  float64
dtypes: float64(4), object(4)
memory usage: 893.7+ KB

In [20]:
!pip install spacy

Collecting spacy
  Downloading spacy-3.8.4-cp311-cp311-win_amd64.whl (12.2 MB)
                                              0.0/12.2 MB ? eta -:--:--
                                             0.0/12.2 MB 991.0 kB/s eta 0:00:13
                                              0.2/12.2 MB 2.1 MB/s eta 0:00:06
                                              0.3/12.2 MB 2.0 MB/s eta 0:00:07
     -                                        0.4/12.2 MB 2.5 MB/s eta 0:00:05
     -                                        0.6/12.2 MB 2.4 MB/s eta 0:00:05
     --                                       0.7/12.2 MB 2.7 MB/s eta 0:00:05
     --                                       0.9/12.2 MB 2.7 MB/s eta 0:00:05
     ---                                      1.1/12.2 MB 3.0 MB/s eta 0:00:04
     ----                                     1.3/12.2 MB 3.0 MB/s eta 0:00:04
     ----                                     1.4/12.2 MB 3.1 MB/s eta 0:00:04
     -----                                    1.7/12.2 MB 3.2 MB/s eta 0:00:04
     ------                                   1.9/12.2 MB 3.4 MB/s eta 0:00:04
     ------                                   2.1/12.2 MB 3.4 MB/s eta 0:00:03
     -------                                  2.3/12.2 MB 3.5 MB/s eta 0:00:03
     --------                                 2.5/12.2 MB 3.6 MB/s eta 0:00:03
     ---------                                2.8/12.2 MB 3.8 MB/s eta 0:00:03
     ----------                               3.1/12.2 MB 3.9 MB/s eta 0:00:03
     ----------                               3.3/12.2 MB 3.9 MB/s eta 0:00:03
     ------------                             3.7/12.2 MB 4.1 MB/s eta 0:00:03
     -------------                            4.0/12.2 MB 4.2 MB/s eta 0:00:02
     -------------                            4.2/12.2 MB 4.2 MB/s eta 0:00:02
     --------------                           4.5/12.2 MB 4.4 MB/s eta 0:00:02
     ---------------                          4.9/12.2 MB 4.4 MB/s eta 0:00:02
     -----------------                        5.2/12.2 MB 4.6 MB/s eta 0:00:02
     ------------------                       5.6/12.2 MB 4.7 MB/s eta 0:00:02
     -------------------                      5.8/12.2 MB 4.7 MB/s eta 0:00:02
     --------------------                     6.3/12.2 MB 4.9 MB/s eta 0:00:02
     ----------------------                   6.7/12.2 MB 5.1 MB/s eta 0:00:02
     -----------------------                  7.2/12.2 MB 5.2 MB/s eta 0:00:01
     ------------------------                 7.5/12.2 MB 5.3 MB/s eta 0:00:01
     -------------------------                7.8/12.2 MB 5.4 MB/s eta 0:00:01
     ---------------------------              8.5/12.2 MB 5.6 MB/s eta 0:00:01
     ----------------------------             8.8/12.2 MB 5.6 MB/s eta 0:00:01
     ------------------------------           9.2/12.2 MB 5.7 MB/s eta 0:00:01
     ------------------------------           9.5/12.2 MB 5.7 MB/s eta 0:00:01
     --------------------------------         9.8/12.2 MB 5.8 MB/s eta 0:00:01
     ---------------------------------        10.2/12.2 MB 5.8 MB/s eta 0:00:01
     ----------------------------------       10.5/12.2 MB 6.2 MB/s eta 0:00:01
     -----------------------------------      10.9/12.2 MB 6.4 MB/s eta 0:00:01
     ------------------------------------     11.3/12.2 MB 6.6 MB/s eta 0:00:01
     -------------------------------------    11.6/12.2 MB 6.8 MB/s eta 0:00:01
     --------------------------------------   11.8/12.2 MB 6.9 MB/s eta 0:00:01
     ---------------------------------------  12.2/12.2 MB 7.0 MB/s eta 0:00:01
     ---------------------------------------- 12.2/12.2 MB 6.7 MB/s eta 0:00:00
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.12-cp311-cp311-win_amd64.whl (25 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.11-cp311-cp311-win_amd64.whl (39 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.9-cp311-cp311-win_amd64.whl (122 kB)
                                              0.0/122.3 kB ? eta -:--:--
     -------------------------------------- 122.3/122.3 kB 7.0 MB/s eta 0:00:00
Collecting thinc<8.4.0,>=8.3.4 (from spacy)
  Downloading thinc-8.3.4-cp311-cp311-win_amd64.whl (1.5 MB)
                                              0.0/1.5 MB ? eta -:--:--
     -------                                  0.3/1.5 MB 5.7 MB/s eta 0:00:01
     -----------                              0.4/1.5 MB 5.3 MB/s eta 0:00:01
     ----------------                         0.6/1.5 MB 4.3 MB/s eta 0:00:01
     -----------------------                  0.9/1.5 MB 4.7 MB/s eta 0:00:01
     -------------------------------          1.2/1.5 MB 4.9 MB/s eta 0:00:01
     --------------------------------------   1.4/1.5 MB 5.1 MB/s eta 0:00:01
     ---------------------------------------- 1.5/1.5 MB 4.7 MB/s eta 0:00:00
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Downloading srsly-2.5.1-cp311-cp311-win_amd64.whl (632 kB)
                                              0.0/632.6 kB ? eta -:--:--
     -----------------                      286.7/632.6 kB 5.9 MB/s eta 0:00:01
     -----------------------------------    583.7/632.6 kB 7.3 MB/s eta 0:00:01
     -------------------------------------- 632.6/632.6 kB 5.7 MB/s eta 0:00:00
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Collecting weasel<0.5.0,>=0.1.0 (from spacy)
  Downloading weasel-0.4.1-py3-none-any.whl (50 kB)
                                              0.0/50.3 kB ? eta -:--:--
     ---------------------------------------- 50.3/50.3 kB ? eta 0:00:00
Collecting typer<1.0.0,>=0.3.0 (from spacy)
  Downloading typer-0.15.1-py3-none-any.whl (44 kB)
                                              0.0/44.9 kB ? eta -:--:--
     ---------------------------------------- 44.9/44.9 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\harsha\anaconda3\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in c:\users\harsha\anaconda3\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\harsha\anaconda3\lib\site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\harsha\anaconda3\lib\site-packages (from spacy) (2.7.0)
Requirement already satisfied: jinja2 in c:\users\harsha\anaconda3\lib\site-packages (from spacy) (3.1.2)
Requirement already satisfied: setuptools in c:\users\harsha\anaconda3\lib\site-packages (from spacy) (67.8.0)
Requirement already satisfied: packaging>=20.0 in c:\users\harsha\anaconda3\lib\site-packages (from spacy) (23.1)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy)
  Downloading langcodes-3.5.0-py3-none-any.whl (182 kB)
                                              0.0/183.0 kB ? eta -:--:--
     -------------------------------------- 183.0/183.0 kB 5.6 MB/s eta 0:00:00
Collecting language-data>=1.2 (from langcodes<4.0.0,>=3.2.0->spacy)
  Downloading language_data-1.3.0-py3-none-any.whl (5.4 MB)
                                              0.0/5.4 MB ? eta -:--:--
     -                                        0.3/5.4 MB 16.4 MB/s eta 0:00:01
     ---                                      0.5/5.4 MB 6.6 MB/s eta 0:00:01
     ------                                   0.8/5.4 MB 6.5 MB/s eta 0:00:01
     -------                                  1.0/5.4 MB 5.8 MB/s eta 0:00:01
     ---------                                1.2/5.4 MB 5.6 MB/s eta 0:00:01
     -----------                              1.6/5.4 MB 5.8 MB/s eta 0:00:01
     --------------                           1.9/5.4 MB 6.1 MB/s eta 0:00:01
     ----------------                         2.2/5.4 MB 6.0 MB/s eta 0:00:01
     -----------------                        2.4/5.4 MB 5.9 MB/s eta 0:00:01
     -------------------                      2.7/5.4 MB 5.9 MB/s eta 0:00:01
     ----------------------                   3.0/5.4 MB 6.0 MB/s eta 0:00:01
     ------------------------                 3.3/5.4 MB 6.1 MB/s eta 0:00:01
     --------------------------               3.6/5.4 MB 6.0 MB/s eta 0:00:01
     ----------------------------             3.9/5.4 MB 6.1 MB/s eta 0:00:01
     ------------------------------           4.2/5.4 MB 5.9 MB/s eta 0:00:01
     --------------------------------         4.4/5.4 MB 5.8 MB/s eta 0:00:01
     ----------------------------------       4.7/5.4 MB 6.0 MB/s eta 0:00:01
     ------------------------------------     5.0/5.4 MB 6.0 MB/s eta 0:00:01
     ---------------------------------------  5.3/5.4 MB 6.0 MB/s eta 0:00:01
     ---------------------------------------  5.4/5.4 MB 6.0 MB/s eta 0:00:01
     ---------------------------------------- 5.4/5.4 MB 5.7 MB/s eta 0:00:00
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\harsha\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.18.1 in c:\users\harsha\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.18.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\harsha\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\harsha\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\harsha\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\harsha\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\harsha\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2023.7.22)
Collecting blis<1.3.0,>=1.2.0 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading blis-1.2.0-cp311-cp311-win_amd64.whl (6.2 MB)
                                              0.0/6.2 MB ? eta -:--:--
     --                                       0.4/6.2 MB 11.2 MB/s eta 0:00:01
     ---                                      0.6/6.2 MB 7.7 MB/s eta 0:00:01
     -----                                    0.9/6.2 MB 7.2 MB/s eta 0:00:01
     -------                                  1.2/6.2 MB 6.7 MB/s eta 0:00:01
     ---------                                1.5/6.2 MB 6.6 MB/s eta 0:00:01
     ----------                               1.7/6.2 MB 5.9 MB/s eta 0:00:01
     ------------                             2.0/6.2 MB 6.3 MB/s eta 0:00:01
     --------------                           2.3/6.2 MB 6.2 MB/s eta 0:00:01
     ----------------                         2.5/6.2 MB 6.2 MB/s eta 0:00:01
     ------------------                       2.8/6.2 MB 6.2 MB/s eta 0:00:01
     -------------------                      3.1/6.2 MB 6.2 MB/s eta 0:00:01
     ---------------------                    3.3/6.2 MB 6.2 MB/s eta 0:00:01
     -----------------------                  3.6/6.2 MB 6.2 MB/s eta 0:00:01
     ------------------------                 3.9/6.2 MB 6.2 MB/s eta 0:00:01
     --------------------------               4.1/6.2 MB 6.3 MB/s eta 0:00:01
     ----------------------------             4.4/6.2 MB 6.4 MB/s eta 0:00:01
     -----------------------------            4.6/6.2 MB 6.3 MB/s eta 0:00:01
     -------------------------------          5.0/6.2 MB 6.5 MB/s eta 0:00:01
     ---------------------------------        5.3/6.2 MB 6.5 MB/s eta 0:00:01
     ------------------------------------     5.6/6.2 MB 6.4 MB/s eta 0:00:01
     --------------------------------------   5.9/6.2 MB 6.4 MB/s eta 0:00:01
     ---------------------------------------  6.2/6.2 MB 6.5 MB/s eta 0:00:01
     ---------------------------------------- 6.2/6.2 MB 6.2 MB/s eta 0:00:00
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading confection-0.1.5-py3-none-any.whl (35 kB)
Requirement already satisfied: colorama in c:\users\harsha\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\harsha\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.0.4)
Collecting shellingham>=1.3.0 (from typer<1.0.0,>=0.3.0->spacy)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Requirement already satisfied: rich>=10.11.0 in c:\users\harsha\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (13.7.1)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.1.0->spacy)
  Downloading cloudpathlib-0.20.0-py3-none-any.whl (52 kB)
                                              0.0/52.5 kB ? eta -:--:--
     ---------------------------------------- 52.5/52.5 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\harsha\anaconda3\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\harsha\anaconda3\lib\site-packages (from jinja2->spacy) (2.1.1)
Collecting marisa-trie>=1.1.0 (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy)
  Downloading marisa_trie-1.2.1-cp311-cp311-win_amd64.whl (152 kB)
                                              0.0/152.0 kB ? eta -:--:--
     -------------------------------------- 152.0/152.0 kB 4.6 MB/s eta 0:00:00
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\harsha\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\harsha\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\harsha\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)
Installing collected packages: cymem, wasabi, spacy-loggers, spacy-legacy, shellingham, murmurhash, marisa-trie, cloudpathlib, catalogue, blis, srsly, preshed, language-data, typer, langcodes, confection, weasel, thinc, spacy
Successfully installed blis-1.2.0 catalogue-2.0.10 cloudpathlib-0.20.0 confection-0.1.5 cymem-2.0.11 langcodes-3.5.0 language-data-1.3.0 marisa-trie-1.2.1 murmurhash-1.0.12 preshed-3.0.9 shellingham-1.5.4 spacy-3.8.4 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.1 thinc-8.3.4 typer-0.15.1 wasabi-1.1.3 weasel-0.4.1

In [21]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
                                              0.0/12.8 MB ? eta -:--:--
                                             0.0/12.8 MB 991.0 kB/s eta 0:00:13
                                              0.1/12.8 MB 1.4 MB/s eta 0:00:09
     -                                        0.3/12.8 MB 2.3 MB/s eta 0:00:06
     -                                        0.6/12.8 MB 3.1 MB/s eta 0:00:04
     ---                                      1.1/12.8 MB 4.5 MB/s eta 0:00:03
     -----                                    1.7/12.8 MB 6.0 MB/s eta 0:00:02
     ------                                   2.0/12.8 MB 6.4 MB/s eta 0:00:02
     -------                                  2.3/12.8 MB 6.2 MB/s eta 0:00:02
     --------                                 2.8/12.8 MB 6.5 MB/s eta 0:00:02
     ----------                               3.3/12.8 MB 7.0 MB/s eta 0:00:02
     -----------                              3.5/12.8 MB 7.0 MB/s eta 0:00:02
     -------------                            4.4/12.8 MB 7.9 MB/s eta 0:00:02
     ---------------                          4.9/12.8 MB 8.0 MB/s eta 0:00:01
     ----------------                         5.4/12.8 MB 8.2 MB/s eta 0:00:01
     ------------------                       5.9/12.8 MB 8.4 MB/s eta 0:00:01
     -------------------                      6.4/12.8 MB 8.7 MB/s eta 0:00:01
     --------------------                     6.6/12.8 MB 8.2 MB/s eta 0:00:01
     -----------------------                  7.4/12.8 MB 8.8 MB/s eta 0:00:01
     ------------------------                 7.8/12.8 MB 8.7 MB/s eta 0:00:01
     -------------------------                8.1/12.8 MB 8.5 MB/s eta 0:00:01
     --------------------------               8.4/12.8 MB 8.5 MB/s eta 0:00:01
     ---------------------------              8.8/12.8 MB 8.6 MB/s eta 0:00:01
     ----------------------------             9.3/12.8 MB 8.6 MB/s eta 0:00:01
     ------------------------------           9.7/12.8 MB 8.6 MB/s eta 0:00:01
     -------------------------------          10.1/12.8 MB 8.6 MB/s eta 0:00:01
     --------------------------------         10.4/12.8 MB 9.1 MB/s eta 0:00:01
     --------------------------------         10.4/12.8 MB 9.2 MB/s eta 0:00:01
     ---------------------------------        10.7/12.8 MB 9.1 MB/s eta 0:00:01
     ----------------------------------       10.9/12.8 MB 8.8 MB/s eta 0:00:01
     -----------------------------------      11.3/12.8 MB 8.8 MB/s eta 0:00:01
     ------------------------------------     11.6/12.8 MB 8.5 MB/s eta 0:00:01
     ------------------------------------     11.8/12.8 MB 8.4 MB/s eta 0:00:01
     --------------------------------------   12.2/12.8 MB 8.5 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 8.5 MB/s eta 0:00:01
     ---------------------------------------  12.8/12.8 MB 8.6 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 8.1 MB/s eta 0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [22]:
import spacy
import re

In [23]:
nlp = spacy.load("en_core_web_sm")

In [36]:
import spacy
import re

nlp = spacy.load("en_core_web_sm")

def extract_parameters(user_input):
    # Process the original input for entity recognition
    doc = nlp(user_input)

    location = None
    max_price = None
    min_sqft = None

    # Loop over detected entities
    for ent in doc.ents:
        if ent.label_ == "GPE":
            if location is None:
                location = ent.text
        elif ent.label_ in ["MONEY", "CARDINAL"]:
            text_lower = ent.text.lower()
            if "lakh" in text_lower or "crore" in text_lower:
                # Remove non-digit characters for conversion
                price_text = re.sub(r'[^\d.]', '', text_lower)
                try:
                    if "lakh" in text_lower:
                        # Convert lakhs to thousands: 1 lakh = 100 thousands
                        max_price = float(price_text) * 100  
                    elif "crore" in text_lower:
                        # Convert crores to thousands: 1 crore = 10000 thousands
                        max_price = float(price_text) * 10000
                except ValueError:
                    pass
            else:
                # Treat as thousands if no unit is specified
                try:
                    max_price = float(ent.text)
                except ValueError:
                    pass

    # Use regex for sqft extraction on lowercased text
    match = re.search(r'(\d{3,5})\s*(sqft|square feet|sq ft)?', user_input.lower())
    if match:
        min_sqft = int(match.group(1))

    return {"location": location, "max_price": max_price, "min_sqft": min_sqft}

# Test with a sample query
user_query = "Show me houses in Whitefield under 231 lakhs at least 1521 sqft"
params = extract_parameters(user_query)
print(params)

{'location': 'Whitefield', 'max_price': 231.0, 'min_sqft': 231}

In [28]:
df['price']

0         39.07
1        120.00
2         62.00
3         95.00
4         51.00
          ...
13314    112.00
13315    231.00
13317     60.00
13318    488.00
13319     17.00
Name: price, Length: 12710, dtype: float64

In [37]:
from sklearn.preprocessing import MinMaxScaler

In [38]:
features = ['price','total_sqft']

In [39]:
scalar = MinMaxScaler()

In [40]:
df_scaled = df.copy()

In [42]:
df_scaled['price'] = pd.to_numeric(df_scaled['price'], errors='coerce')
df_scaled['total_sqft'] = pd.to_numeric(df_scaled['total_sqft'], errors='coerce')

In [43]:
df_scaled.dropna(subset= features, inplace=True)

In [44]:
df_scaled[features] = scalar.fit_transform(df_scaled[features])

In [45]:
df_scaled[features].head()

      price  total_sqft
0  0.010699    0.020108
1  0.038567    0.049649
2  0.018595    0.027455
3  0.029959    0.029005
4  0.014807    0.022863

In [48]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def get_similar_houses_with_location(filtered_df, df_scaled, target_index, top_n=5):
    
    # Extract the feature matrix from the scaled DataFrame for houses in the filtered subset.
    feature_matrix = df_scaled.loc[filtered_df.index, ['price', 'total_sqft']].values
    
    # Compute cosine similarity among these houses.
    similarity_matrix = cosine_similarity(feature_matrix)
    
    # Get similarity scores for the target house.
    target_similarity = similarity_matrix[target_index]
    
    # Get indices for top similar houses, excluding the target itself.
    similar_indices = np.argsort(-target_similarity)[1:top_n+1]
    
    # Map these indices back to the filtered DataFrame.
    similar_houses = filtered_df.iloc[similar_indices]
    
    return similar_houses

# Example usage:
# Filter the DataFrame by location (and other criteria if needed)
filtered = query_houses(df, location="Whitefield", max_price=231, min_sqft=1521)

if not filtered.empty:
    # Let's choose the first house in the filtered results as our target.
    similar = get_similar_houses_with_location(filtered, df_scaled, target_index=0, top_n=5)
    print("Top similar houses in the selected location:")
    print(similar[['location', 'price', 'total_sqft']])
else:
    print("No houses found in the specified location with the given criteria.")

Top similar houses in the selected location:
         location  price  total_sqft
6853   Whitefield   63.0      1608.0
8814   Whitefield   68.0      1770.0
1144   Whitefield   75.0      1985.0
2975   Whitefield   75.0      1896.0
11433  Whitefield   68.0      1634.0

In [58]:
def generate_response(filtered_df, similar_houses, location, max_price, min_sqft):
    if filtered_df.empty:
        return f"Sorry, we couldn't find any houses in {location} under {max_price} (in lakhs) with at least {min_sqft} sqft."
    
    response = f"Here are some recommended houses in {location} (with price up to {max_price} and size at least {min_sqft} sqft):\n\n"
    for idx, row in similar_houses.iterrows():
        response += (f"- {row['area_type']} in {row['location']} has {row['total_sqft']} sqft, "
                     f"priced at {row['price']} (in lakhs), and is available {row['availability']}.\n")
    return response


def chatbot():
    user_query = input("Enter your query: ")  # e.g., "Show me houses in Whitefield under 231 at least 1521 sqft"
    
    
    params = extract_parameters(user_query)
    location = params.get("location")
    max_price = params.get("max_price")
    min_sqft = params.get("min_sqft")
    
   
    filtered = query_houses(df, location=location, max_price=max_price, min_sqft=min_sqft)
    
    if filtered.empty:
        print(f"Sorry, we couldn't find any houses in {location} under {max_price} with at least {min_sqft} sqft.")
        return
    
   
    target_index = 0
    similar = get_similar_houses_with_location(filtered, df_scaled, target_index, top_n=5)
    
    
    response = generate_response(filtered, similar, location, max_price, min_sqft)
    print("\n" + response)


if __name__ == "__main__":
    chatbot()

Enter your query: Find me houses near Hebbal with 3 bed rooms
Sorry, we couldn't find any houses in Hebbal under 3.0 with at least None sqft.

In [60]:
def chatbot():
    user_query = input("Enter your query: ")  # e.g., "Show me houses in Whitefield under 231 at least 1521 sqft"
    
    params = extract_parameters(user_query)
    location = params.get("location")
    max_price = params.get("max_price")
    min_sqft = params.get("min_sqft")
    
    if not location or not max_price or not min_sqft:
        print("I couldn't extract all necessary details. Please include location, price, and sqft in your query.")
        return

    filtered = query_houses(df, location=location, max_price=max_price, min_sqft=min_sqft)
    
    if filtered.empty:
        print(f"Sorry, no houses found in {location} under {max_price} (in lakhs) with at least {min_sqft} sqft.")
        return

    target_index = 0  
    similar_houses = get_similar_houses_with_location(filtered, df_scaled, target_index, top_n=5)
    
    response = generate_response(filtered, similar_houses, location, max_price, min_sqft)
    print("\n" + response)

if __name__ == "__main__":
    chatbot()

Enter your query: Find me houses near Malleshwaram under 70 lakh up to 1000 sqft

Here are some recommended houses in Malleshwaram (with price up to 1000.0 and size at least 1000 sqft):

- Built-up  Area in Malleshwaram has 1124.0 sqft, priced at 80.0 (in lakhs), and is available Ready To Move.
- Super built-up  Area in Malleshwaram has 2520.0 sqft, priced at 150.0 (in lakhs), and is available Ready To Move.
- Super built-up  Area in Malleshwaram has 2425.0 sqft, priced at 140.0 (in lakhs), and is available Ready To Move.
- Super built-up  Area in Malleshwaram has 1020.0 sqft, priced at 80.0 (in lakhs), and is available Ready To Move.
- Super built-up  Area in Malleshwaram has 1410.0 sqft, priced at 125.0 (in lakhs), and is available Ready To Move.